DROP TABLE IF EXISTS STUDENT;
CREATE TABLE STUDENT (
	ID BIGSERIAL PRIMARY KEY,
	FIRSTNAME VARCHAR(50),
	LASTNAME VARCHAR(50),
	EMAIL VARCHAR(50),
	PASSWORD VARCHAR(15),
	FACULTY VARCHAR(20),
	YEAROFSTUDY INTEGER,
	ALBUMNUMBER INTEGER
);

DROP TABLE IF EXISTS COURSE;
CREATE TABLE COURSE (
	ID BIGSERIAL PRIMARY KEY,
	TITLE VARCHAR(255),
	TERM DATE
);

DROP TABLE IF EXISTS PRESENCE;
CREATE TABLE PRESENCE (
	ID BIGSERIAL PRIMARY KEY,
	COURSE_ID INTEGER,
	STUDENT_ID INTEGER
);